eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

microservice:
  employee-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/placeOrder
  department-service:
    endpoints:
      i:endpoint:
        ur http://PAYMENT-SERVICE/payment/payment
